version: '2.1'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    ports:
      - "9200:9200"
      - "9300:9300"
    network_mode: host
    healthcheck:
      test: curl -f http://localhost:9200
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
      xpack.monitoring.enabled: "true"
      SERVER_NAME: "elasticsearch"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
      
  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      monitoring.ui.container.elasticsearch.enabled: "true"
      server.host: "0"
    depends_on:
      - elasticsearch

  portal-busca:
    image: luminihire.web
    ports:
      - "5000:80"
      - "5001:443"
    build:
      context: .
    depends_on:
      - elasticsearch
    network_mode: host

  carga-elastic:
    image: luminihire.seed
    build:
      context: .
      dockerfile: ./src/LuminiHire.ElasticSearch.Seed/Dockerfile
    depends_on:
      - elasticsearch
    network_mode: host
    
volumes:
  esdata:
    driver: local