version: '3.7'
services:
  carga-elastic:
    image: luminihire.elasticsearch.seed
    build:
      context: ./src/LuminiHire.ElasticSearch.Seed
    depends_on:
      - "elasticsearch"
  portal-busca:
    image: luminihire.web
    build:
      context: ./src/LuminiHire
    depends_on:
      - "carga-elastic"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
      xpack.monitoring.enabled: "true"
      SERVER_NAME: "elasticsearch"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
      
  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      monitoring.ui.container.elasticsearch.enabled: "true"
      server.host: "0"
    depends_on:
      - elasticsearch
      
volumes:
  esdata:
    driver: local